### ISSUE TITLE
Rework the Account menu appearance and layout in the Header block.

### ISSUE THREAD

**Issue by wesruv** [backdrop-contrib/basis#4]

**Comment by Graham-72** [comment]
Is this the right issue to add my comment? Started a new site but have no logo yet, but Basis has left a gap. Would be nicer not to have this gap. Also. might be nicer to have My Account and Log out on the right perhaps. CSS here I come!
![welcome to kyson fairways - kyson fairways 2016-04-15 17-44-46](https://cloud.githubusercontent.com/assets/10559274/14568606/d387f15a-0331-11e6-93c9-bcf8ef1abdd9.png)

**Comment by Graham-72** [comment]
Maybe I had done something wrong because today I have added a temporary logo and the 'My account' etc has moved. But my immediate next wish is to add a banner image.
![welcome to kyson fairways - kyson fairways 2016-04-18 14-55-07](https://cloud.githubusercontent.com/assets/10559274/14606669/21528904-0576-11e6-9dbd-e38860999cbe.png)

**Comment by Graham-72** [comment]
@wesruv I have been getting on well with Basis and liking it a lot, creating sub-themes for a couple of sites using CSS to arrange things in the header. Here is a screenshot of my current result
![kyson river deben fairways committee - kyson fairways 2016-04-21 05-49-06](https://cloud.githubusercontent.com/assets/10559274/14698287/597b6100-0785-11e6-978f-26961363005e.png)
I have now hit a problem when checking how it will look on a small screen, partly because I do not yet fully understand how Basis is managing the break points as screen gets narrower but also I have now found when using my Android tablet that I get erratic results, and these differ depending on whether I am using the Android browser app 'Internet' or Google's Chrome app.

I realise this is work in progress - just thought I should post this feedback somewhere. Please carry on with this theme. I like it a lot, and have been using single and two-column layouts so far.

**Comment by wesruv** [comment]
@graham-72 that is because I haven't put in the fallback to float instead of flexbox yet. The CSS is there, but will need to do some feature detection to load it.

**Comment by wesruv** [comment]
See issue #2

**Comment by wesruv** [comment]
Oh, I didn't answer your question about how the grid breakpoints work. 

It's using grid utility classes like bootstrap 3. If you look in templates/layout you'll see classes like:
l-content l-col-xs-12 l-col-lg-6 l-order-lg-1

l-content is the region name

 l-col-xs-12 l-col-lg-6 
These two define how wide these columns should be at what breakpoint. It's mobile first, so if you define a column width with one of these classes it'll apply to that breakpoint and up, unless you add a class at a higher breakpoint. 

So this column is full width starting at mobile, and at large breakpoint it becomes half width. 

l-order-lg-1
This is a flexbox feature. You can change the order elements appear based on a weight. Higher numbers means layer in the list. Since in this layout the source order and column order need to be different, order is used to weight this column so it'll assist second in the 3 3 4 layout.

**Comment by wesruv** [comment]
Also note that the order class has an lg for large breakpoint. This "weight" doesn't apply until desktop sizes. 

I need to write docs ... We strayed a bit from bootstrap. The class naming is slightly different (we added an l- prefix), and bootstrap doesn't have classes for order.

**Comment by Graham-72** [comment]
Thanks very much for this. :+1:

**Comment by wesruv** [comment]
Sorry for the comment spam, I responded to this in a waiting room in a gov't office.

I just saw your original comment from 6 days ago, when I set this up I was shooting for what I wanted a Backdrop first run experience to be like, which had specific config/content setup. I thought I had gone back and assumed our current first run experience with it's config/setup but your screenshot shows what it looked like before that work.

I'll have to take another look at what I've got. Going to do a lot of work on this in the coming week.

**Comment by Graham-72** [comment]
@wesruv certainly not spam from my point of view. I may perhaps have started with the wrong version of your files. I have loaded them as an alternative theme, and am using Basis as the base theme for a couple of simple sites.

As the premier out-of-the box theme I guess I would like something that matched my thought process when starting a site. I want -
1. a banner image than I can replace with one of my own.
2. optional display, placing and alignment of site title, slogan, logo.
3. optional display, placing and alignment of primary and account menus, and breadcrumb.

Maybe this is too much to ask for. In practice I am very happy to add a bit of custom CSS but that's not so easy for some to manage.

I have now forked your repo into PhpStorm so will try and track your changes over the next few days. Thanks for what you are doing.

**Comment by Graham-72** [comment]
@wesruv I thought you might like to see where I have got to with using Basis. It's at www.kysonfairways.org.uk. My client likes it; I like it, except I want to get its layout working properly on small screens before I publicize it.

**Comment by wesruv** [comment]
@Graham-72 that looks great! I wonder if the updates I've made to theme would help with that a bit?

I'd back up the existing version of basis that you're using in case my changes mess you up :fearful: 

I definitely need to work on getting the ['float' fallback in](https://github.com/backdrop-contrib/basis/issues/2), which should be done soon.

**Comment by wesruv** [comment]
Re: the subject of this task, the account menu and Header block.

I tried a whole bunch of hacks to get the account menu to appear in the top right... it was an enormous pain. I decided to stop fighting the source order/layout and I'm treating the `header-menu` the same way I'm treating the main menu.

There isn't a clear use case for what the header menu should be, and I don't want to make bad assumptions.

![image](https://cloud.githubusercontent.com/assets/5607236/14771146/f19b570c-0a4f-11e6-9126-3dd6444dffed.png)

I think it's the best I can do with what I've got, ideally a site will use the header block or a separate main-menu block, but not both, and before long I hope we change the default config to something that makes a bit more sense.
