### ISSUE TITLE
Style the Draggable table updated row

### ISSUE THREAD

**Issue by wesruv** [backdrop-contrib/basis#5]
![image](https://cloud.githubusercontent.com/assets/5607236/13485889/fd9c3552-e0d9-11e5-9772-ce5fdd829d4f.png)

**Comment by wesruv** [comment]
The re-order icon isn't very popular, going to go back to the old crusty one.

**Comment by klonos** [comment]
It's not a matter of popularity @wesruv ...well, in fact it rather is! You see, this icon is used for many things over various UIs and it has over time become popular for these. So much that we might end up confusing people and since Basis is target for inclusion in core, this should be a major concern.

If you exclude iOS (which, contrary to fruit-lovers' belief, seems to [hold only a rough ~15% of the market](https://www.google.com/search?q=ios+market+share)), then I think that the most popular use cases for the "hamburger" icon is mobile menus and justified text.

There are better alternatives that we can consider to use instead that IMO make a lot more sense:
- [up/down arrow(s)](https://www.google.com/search?q=up+down+arrow):

![arrow_up_down](https://cloud.githubusercontent.com/assets/2423362/14757714/e4bc13ee-0939-11e6-9b2e-04166571dff7.png)
![arrow-double-up-down](https://cloud.githubusercontent.com/assets/2423362/14757715/e4be2b7a-0939-11e6-95ed-45c35f46efc0.png)
![arrow-up-down](https://cloud.githubusercontent.com/assets/2423362/14757717/e4c2ee1c-0939-11e6-9631-c07e0e9ed30e.png)
![up_down_arrow](https://cloud.githubusercontent.com/assets/2423362/14757716/e4c2e3e0-0939-11e6-9d7c-5130c3fcdc03.png)
- cross cursor for draggable items that can be moved up/down as well as left/right like (what we currently have in place):

![arrow-all](https://cloud.githubusercontent.com/assets/2423362/14757720/ee607ade-0939-11e6-8c23-49c49cd2d84b.png)
- list with up/down arrows (I think that having the first/last items be only down/up respectively is cool):

![list_reorder_down](https://cloud.githubusercontent.com/assets/2423362/14757724/fb47f092-0939-11e6-837f-80769fb48f70.png)
![list_reorder-up-down](https://cloud.githubusercontent.com/assets/2423362/14757726/fb4e8dc6-0939-11e6-93d3-3a601de2192a.png)
![list_reorder_up](https://cloud.githubusercontent.com/assets/2423362/14757725/fb49b49a-0939-11e6-9b4e-f549d5b1705f.png)

![drag_reorder](https://cloud.githubusercontent.com/assets/2423362/14757729/03d6f29e-093a-11e6-8786-455b71f9e568.png)
![drag_reorder-white](https://cloud.githubusercontent.com/assets/2423362/14757730/03df7360-093a-11e6-8dd9-f00cc7b22fab.png)

The last set is like the hamburger icon, but the added arrows help to better distinguish what the intention is I believe.

**Comment by klonos** [comment]
...or my take on it:

![up-down-list](https://cloud.githubusercontent.com/assets/2423362/14758016/56016650-093d-11e6-9ba0-b70857d63090.png)

**Comment by wesruv** [comment]
Some of the lists can be indented (taxonomy), the icons that I was leaning towards, 
![drag_reorder](https://cloud.githubusercontent.com/assets/2423362/14757729/03d6f29e-093a-11e6-8786-455b71f9e568.png)
![drag_reorder-white](https://cloud.githubusercontent.com/assets/2423362/14757730/03df7360-093a-11e6-8dd9-f00cc7b22fab.png)

and your last one don't indicate that. I'm thinking for now I'll stick with the cross cursor, and we can revisit changing it later.
